-- ============================================
-- KDIGO Health State Progression Tracking
-- ============================================
-- This migration adds tables to track patient progression
-- through KDIGO health states over time, enabling:
-- - Longitudinal monitoring
-- - State transition detection
-- - Automated alerts
-- - Treatment recommendations

-- ============================================
-- 1. Health State History
-- ============================================
-- Stores KDIGO classification at each measurement point
CREATE TABLE IF NOT EXISTS health_state_history (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,

    -- Measurement date
    measured_at TIMESTAMP NOT NULL,
    cycle_number INTEGER, -- Month/cycle number for longitudinal tracking (1-24)

    -- Lab values
    egfr_value DECIMAL(5, 2) NOT NULL,
    uacr_value DECIMAL(8, 2), -- May be null if not measured

    -- KDIGO Classification
    gfr_category VARCHAR(5) NOT NULL, -- G1, G2, G3a, G3b, G4, G5
    albuminuria_category VARCHAR(5) NOT NULL, -- A1, A2, A3
    health_state VARCHAR(10) NOT NULL, -- e.g., "G3a-A2"

    -- Risk Assessment
    risk_level VARCHAR(20) NOT NULL, -- low, moderate, high, very_high
    risk_color VARCHAR(10) NOT NULL, -- green, yellow, orange, red

    -- CKD Stage
    ckd_stage INTEGER, -- 1-5, null if not CKD
    ckd_stage_name VARCHAR(50),

    -- Clinical Flags
    requires_nephrology_referral BOOLEAN DEFAULT false,
    requires_dialysis_planning BOOLEAN DEFAULT false,

    -- Treatment Recommendations
    recommend_ras_inhibitor BOOLEAN DEFAULT false,
    recommend_sglt2i BOOLEAN DEFAULT false,
    target_bp VARCHAR(20),
    monitoring_frequency VARCHAR(50),

    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Indexes
    CONSTRAINT health_state_unique UNIQUE (patient_id, measured_at)
);

CREATE INDEX idx_health_state_patient ON health_state_history(patient_id);
CREATE INDEX idx_health_state_date ON health_state_history(measured_at);
CREATE INDEX idx_health_state_cycle ON health_state_history(cycle_number);
CREATE INDEX idx_health_state_risk ON health_state_history(risk_level);
CREATE INDEX idx_health_state_category ON health_state_history(gfr_category, albuminuria_category);

-- ============================================
-- 2. State Transitions
-- ============================================
-- Records when patients move between KDIGO states
CREATE TABLE IF NOT EXISTS state_transitions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,

    -- Transition timing
    transition_date TIMESTAMP NOT NULL,
    from_cycle INTEGER,
    to_cycle INTEGER,

    -- Previous state
    from_health_state VARCHAR(10) NOT NULL,
    from_gfr_category VARCHAR(5) NOT NULL,
    from_albuminuria_category VARCHAR(5) NOT NULL,
    from_risk_level VARCHAR(20) NOT NULL,
    from_egfr DECIMAL(5, 2),
    from_uacr DECIMAL(8, 2),

    -- Current state
    to_health_state VARCHAR(10) NOT NULL,
    to_gfr_category VARCHAR(5) NOT NULL,
    to_albuminuria_category VARCHAR(5) NOT NULL,
    to_risk_level VARCHAR(20) NOT NULL,
    to_egfr DECIMAL(5, 2),
    to_uacr DECIMAL(8, 2),

    -- Change analysis
    change_type VARCHAR(20) NOT NULL, -- improved, worsened, stable
    egfr_change DECIMAL(6, 2), -- Positive = improving
    uacr_change DECIMAL(8, 2), -- Negative = improving
    gfr_trend VARCHAR(20), -- improving, stable, declining
    albuminuria_trend VARCHAR(20), -- improving, stable, worsening, unknown

    -- Severity flags
    category_changed BOOLEAN DEFAULT false,
    risk_changed BOOLEAN DEFAULT false,
    risk_increased BOOLEAN DEFAULT false,
    crossed_critical_threshold BOOLEAN DEFAULT false,

    -- Alert status
    alert_generated BOOLEAN DEFAULT false,
    alert_severity VARCHAR(20), -- info, warning, critical

    -- Metadata
    detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_transitions_patient ON state_transitions(patient_id);
CREATE INDEX idx_transitions_date ON state_transitions(transition_date);
CREATE INDEX idx_transitions_type ON state_transitions(change_type);
CREATE INDEX idx_transitions_alert ON state_transitions(alert_generated, alert_severity);

-- ============================================
-- 3. Monitoring Alerts
-- ============================================
-- Automated alerts generated by the AI monitoring system
CREATE TABLE IF NOT EXISTS monitoring_alerts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    transition_id UUID REFERENCES state_transitions(id) ON DELETE CASCADE,

    -- Alert details
    alert_type VARCHAR(50) NOT NULL, -- state_change, threshold_crossed, rapid_decline, etc.
    severity VARCHAR(20) NOT NULL, -- info, warning, critical
    priority INTEGER DEFAULT 3, -- 1=highest, 5=lowest

    -- Alert message
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    alert_reasons TEXT[], -- Array of reasons for alert

    -- Clinical context
    current_health_state VARCHAR(10),
    previous_health_state VARCHAR(10),
    egfr_value DECIMAL(5, 2),
    uacr_value DECIMAL(8, 2),

    -- Status
    status VARCHAR(20) DEFAULT 'active', -- active, acknowledged, resolved, dismissed
    acknowledged_by VARCHAR(100),
    acknowledged_at TIMESTAMP,
    resolved_at TIMESTAMP,

    -- Action tracking
    requires_action BOOLEAN DEFAULT false,
    action_taken TEXT,
    action_taken_at TIMESTAMP,

    -- Metadata
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_alerts_patient ON monitoring_alerts(patient_id);
CREATE INDEX idx_alerts_status ON monitoring_alerts(status);
CREATE INDEX idx_alerts_severity ON monitoring_alerts(severity, priority);
CREATE INDEX idx_alerts_generated ON monitoring_alerts(generated_at);

-- ============================================
-- 4. Action Recommendations
-- ============================================
-- AI-generated recommendations based on state changes
CREATE TABLE IF NOT EXISTS action_recommendations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    alert_id UUID REFERENCES monitoring_alerts(id) ON DELETE CASCADE,
    transition_id UUID REFERENCES state_transitions(id) ON DELETE CASCADE,

    -- Recommendation details
    recommendation_type VARCHAR(50) NOT NULL, -- monitoring, treatment, referral, lifestyle
    category VARCHAR(50) NOT NULL, -- lab_monitoring, medication, specialist_referral, etc.

    -- Recommendation content
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    rationale TEXT NOT NULL, -- Why this is recommended

    -- Priority and urgency
    priority INTEGER DEFAULT 3, -- 1=highest, 5=lowest
    urgency VARCHAR(20) DEFAULT 'routine', -- urgent, semi_urgent, routine
    timeframe VARCHAR(100), -- e.g., "Within 1 week", "Within 3 months"

    -- Clinical parameters
    based_on_health_state VARCHAR(10),
    based_on_risk_level VARCHAR(20),
    triggered_by TEXT[], -- Array of triggering factors

    -- Specific actions
    action_items JSONB, -- Structured action items
    /* Example structure:
    {
      "lab_tests": ["uACR", "eGFR", "serum creatinine"],
      "medications": {
        "start": ["lisinopril", "empagliflozin"],
        "adjust": ["metformin"]
      },
      "referrals": ["nephrology"],
      "monitoring_frequency": "Every 3 months"
    }
    */

    -- Status
    status VARCHAR(20) DEFAULT 'pending', -- pending, in_progress, completed, dismissed
    implemented_by VARCHAR(100),
    implemented_at TIMESTAMP,
    completion_notes TEXT,

    -- Effectiveness tracking
    outcome VARCHAR(50), -- improved, stabilized, declined, unknown
    outcome_notes TEXT,

    -- Metadata
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_recommendations_patient ON action_recommendations(patient_id);
CREATE INDEX idx_recommendations_status ON action_recommendations(status);
CREATE INDEX idx_recommendations_type ON action_recommendations(recommendation_type);
CREATE INDEX idx_recommendations_priority ON action_recommendations(priority, urgency);
CREATE INDEX idx_recommendations_generated ON action_recommendations(generated_at);

-- ============================================
-- 5. Progression Analytics View
-- ============================================
-- Materialized view for quick progression analysis
CREATE MATERIALIZED VIEW IF NOT EXISTS patient_progression_summary AS
SELECT
    p.id AS patient_id,
    p.medical_record_number,
    p.first_name,
    p.last_name,

    -- Current state (most recent)
    (SELECT health_state FROM health_state_history
     WHERE patient_id = p.id
     ORDER BY measured_at DESC LIMIT 1) AS current_health_state,

    (SELECT risk_level FROM health_state_history
     WHERE patient_id = p.id
     ORDER BY measured_at DESC LIMIT 1) AS current_risk_level,

    (SELECT egfr_value FROM health_state_history
     WHERE patient_id = p.id
     ORDER BY measured_at DESC LIMIT 1) AS current_egfr,

    (SELECT uacr_value FROM health_state_history
     WHERE patient_id = p.id
     ORDER BY measured_at DESC LIMIT 1) AS current_uacr,

    -- Baseline state (first measurement)
    (SELECT health_state FROM health_state_history
     WHERE patient_id = p.id
     ORDER BY measured_at ASC LIMIT 1) AS baseline_health_state,

    (SELECT egfr_value FROM health_state_history
     WHERE patient_id = p.id
     ORDER BY measured_at ASC LIMIT 1) AS baseline_egfr,

    -- Progression metrics
    (SELECT COUNT(*) FROM state_transitions
     WHERE patient_id = p.id) AS total_transitions,

    (SELECT COUNT(*) FROM state_transitions
     WHERE patient_id = p.id AND change_type = 'worsened') AS worsening_transitions,

    (SELECT COUNT(*) FROM state_transitions
     WHERE patient_id = p.id AND change_type = 'improved') AS improving_transitions,

    (SELECT COUNT(*) FROM monitoring_alerts
     WHERE patient_id = p.id AND status = 'active') AS active_alerts,

    (SELECT COUNT(*) FROM action_recommendations
     WHERE patient_id = p.id AND status = 'pending') AS pending_recommendations,

    -- Timing
    (SELECT MIN(measured_at) FROM health_state_history
     WHERE patient_id = p.id) AS first_measurement,

    (SELECT MAX(measured_at) FROM health_state_history
     WHERE patient_id = p.id) AS last_measurement,

    (SELECT MAX(measured_at) FROM health_state_history
     WHERE patient_id = p.id) -
    (SELECT MIN(measured_at) FROM health_state_history
     WHERE patient_id = p.id) AS monitoring_duration

FROM patients p
WHERE EXISTS (SELECT 1 FROM health_state_history WHERE patient_id = p.id);

CREATE UNIQUE INDEX idx_progression_summary_patient ON patient_progression_summary(patient_id);

-- ============================================
-- 6. Helper Functions
-- ============================================

-- Function to refresh the progression summary view
CREATE OR REPLACE FUNCTION refresh_progression_summary()
RETURNS void AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY patient_progression_summary;
END;
$$ LANGUAGE plpgsql;

-- Function to get patient's progression trend
CREATE OR REPLACE FUNCTION get_progression_trend(p_patient_id UUID, p_months INTEGER DEFAULT 6)
RETURNS TABLE (
    measurement_date TIMESTAMP,
    egfr DECIMAL,
    uacr DECIMAL,
    health_state VARCHAR,
    risk_level VARCHAR
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        h.measured_at,
        h.egfr_value,
        h.uacr_value,
        h.health_state,
        h.risk_level
    FROM health_state_history h
    WHERE h.patient_id = p_patient_id
    AND h.measured_at >= NOW() - (p_months || ' months')::INTERVAL
    ORDER BY h.measured_at ASC;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- Migration Complete
-- ============================================

SELECT 'KDIGO Progression Tracking tables created successfully!' AS status;
